document.addEventListener('DOMContentLoaded', () => {
    window.sr = ScrollReveal({ reset: false })

    sr.reveal('.intro-dlc', { origin: 'right', distance: '100px', duration: 1000 })
    sr.reveal('.p-demo', { origin: 'bottom', distance: '80px', duration: 800 })
    sr.reveal('.topics-container', { origin: 'right', distance: '100px', duration: 1000, delay: 100 })
    sr.reveal('.trailer-container', { origin: 'right', distance: '100px', duration: 1000, delay: 100 })
    sr.reveal('.about', { origin: 'bottom', distance: '800px', duration: 1000 })
    sr.reveal('.imgs-about', { origin: 'bottom', distance: '500px', duration: 1000 })
    sr.reveal('.h2-story', { origin: 'bottom', distance: '200px', duration: 1000 })
    sr.reveal('.p-story', { origin: 'bottom', distance: '200px', duration: 1000, delay: 50 })
    sr.reveal('.character_thumbs', { origin: 'right', distance: '100px', duration: 1200 })
    sr.reveal('.character_info-carousel', { origin: 'bottom', distance: '500px', duration: 1200 })
    sr.reveal('.location_p-container', { origin: 'bottom', distance: '100px', duration: 1000 })
    sr.reveal('.location-carousel', { origin: 'bottom', distance: '100px', duration: 1000 })
    sr.reveal('.gameplay_info-h2', { origin: 'bottom', distance: '100px', duration: 1000 })
    sr.reveal('.gameplay_info-p-container', { origin: 'bottom', distance: '100px', duration: 1000, delay: 50 })
    sr.reveal('.gameplay_action-carousel-img', { origin: 'bottom', distance: '300px', duration: 1000 })
    sr.reveal('.gameplay_action-carousel-caption', { origin: 'bottom', distance: '300px', duration: 1000 })
    sr.reveal('.gameplay_resource-carousel-img', { origin: 'bottom', distance: '300px', duration: 1000 })
    sr.reveal('.dlc_title-h2', { origin: 'bottom', distance: '100px', duration: 1000 })
    sr.reveal('.dlc_title-p-container', { origin: 'bottom', distance: '100px', duration: 1000, delay: 100 })
    sr.reveal('.separate-ways', { origin: 'bottom', distance: '500px', duration: 1000 })
    sr.reveal('.separate-ways_story-carousel', { origin: 'left', distance: '200px', duration: 1000 })
    sr.reveal('.separate-ways_story_info', { origin: 'bottom', distance: '500px', duration: 1000 })
    sr.reveal('.separate-ways_gameplay_info', { origin: 'bottom', distance: '500px', duration: 1000 })
    sr.reveal('.separate-ways_gameplay-carousel', { origin: 'right', distance: '200px', duration: 1000 })
    sr.reveal('.mercenaries', { origin: 'bottom', distance: '500px', duration: 1000 })
    sr.reveal('.update_release-p', { origin: 'bottom', distance: '200px', duration: 1000 })
    sr.reveal('.update_details', { origin: 'bottom', distance: '200px', duration: 1000 })
    sr.reveal('.characters_title-p', { origin: 'right', distance: '100px', duration: 1000 })
    sr.reveal('.characters', { origin: 'bottom', distance: '300px', duration: 1000 })
    sr.reveal('.vr-mode', { origin: 'bottom', distance: '500px', duration: 1000 })
    sr.reveal('.vr-mode_demo', { origin: 'bottom', distance: '300px', duration: 1000 })
    sr.reveal('.vr-mode_first-carousel', { origin: 'left', distance: '200px', duration: 1000 })
    sr.reveal('.vr-mode_info-1', { origin: 'bottom', distance: '500px', duration: 1000 })
    sr.reveal('.vr-mode_info-2', { origin: 'bottom', distance: '500px', duration: 1000 })
    sr.reveal('.vr-mode_second-carousel', { origin: 'right', distance: '200px', duration: 1000 })
    sr.reveal('.product_title', { origin: 'bottom', distance: '300px', duration: 1000 })
    sr.reveal('.product_box', { origin: 'bottom', distance: '100px', duration: 1000 })
    sr.reveal('.product_edition', { origin: 'bottom', distance: '500px', duration: 1000 })
    sr.reveal('.others_block-1', { origin: 'bottom', distance: '500px', duration: 1000 })
})
